apiVersion: v1
kind: Pod
metadata:
  name: cloud-basic-1-huyifan-1-0
spec:
  containers:
    - name: nginx
      image: nginx:1.14.0
      imagePullPolicy: IfNotPresent
      ports:
      - name: http
        containerPort: 70
        hostPort: 70

---
